Velocloud-Junit_Coverage#5918
IBM/velocloud-sdwan-driver pull request #5
Opened 2022-09-14 05:07 UTC by siddalasha

Results:
[INFO]
[INFO] Tests run: 44, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.4:report (post-unit-test) @ velocloud-sdwan-driver ---
[INFO] Loading execution data file C:\project\velocloud-sdwan-driver\target\test-results\coverage\jacoco\jacoco.exec
[INFO] Analyzed bundle 'velocloud-sdwan-driver' with 53 classes
[INFO]
[INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ velocloud-sdwan-driver ---
[INFO] Building jar: C:\project\velocloud-sdwan-driver\target\velocloud-sdwan-driver-1.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:2.7.1:repackage (repackage) @ velocloud-sdwan-driver ---
[INFO] Replacing main artifact with repackaged archive
[INFO]
[INFO] --- sortpom-maven-plugin:2.8.0:sort (default) @ velocloud-sdwan-driver ---
[INFO] Sorting file C:\project\velocloud-sdwan-driver\pom.xml
[INFO] Pom file is already sorted, exiting
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ velocloud-sdwan-driver ---
[INFO] Installing C:\project\velocloud-sdwan-driver\target\velocloud-sdwan-driver-1.0.1-SNAPSHOT.jar to C:\Users\gsiddala\.m2\repository\com\ibm\velocloud-sdwan-driver\velocloud-sdwan-driver\1.0.1-SNAPSHOT\velocloud-sdwan-driver-1.0.1-SNAPSHOT.jar
[INFO] Installing C:\project\velocloud-sdwan-driver\pom.xml to C:\Users\gsiddala\.m2\repository\com\ibm\velocloud-sdwan-driver\velocloud-sdwan-driver\1.0.1-SNAPSHOT\velocloud-sdwan-driver-1.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.528 s
[INFO] Finished at: 2022-09-14T10:32:22+05:30

2022-09-14 05:24 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +		sdWanDriver.getEdgeConfigurationStack(deploymentLocationProperties, "", "");
What is the expectation after calling sdWanDriver.getEdgeConfigurationStack() method?

2022-09-14 05:31 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +		sdWanDriver.execute(Constants.LIFECYCLE_CREATE, deploymentLocationProperties, "", "");
Where is the getURL() function call?

2022-09-14 05:33 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +	@DisplayName("Testing positive scenario getURL for LIFECYCLE_DELETE")
Is this really a positive scenario?

2022-09-14 05:33 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +		assertThrows(SdwanResponseException.class, ()->{
Here also I don't see getURL() function call which is your objective.

2022-09-14 05:34 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +		assertThrows(SdwanResponseException.class, ()->{
Don't see getURL() call here same as above test case

2022-09-14 05:36 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +	public void executeOperationTest() {
It is not clear what you are testing here. Please add proper Display name content and appropriate tests.

2022-09-14 05:37 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/service/impl/KafkaExternalMessagingServiceImplTest.java
> + 				Duration.ofMillis(100));
What you are testing after making senDelayedExecutionAsynResponse() method?

2022-09-14 05:38 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/service/impl/KafkaInternalMessagingServiceImplTest.java
> +
Can you add any expectations?

2022-09-14 05:38 UTC, lokanalla requested changes
Please rework on the test cases.

2022-09-14 09:58 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +	@DisplayName("Testing positive scenario Execute URL for LIFECYCLE_OPERATION_DELETE_VCE_STATIC_IP")
Is it a positive scenario? I see you are asserting Exception.

2022-09-14 09:58 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +	@DisplayName("Testing positive scenario for ExecuteEdge - with exception")
This looks positive scenario.

2022-09-14 10:00 UTC, lokanalla commented on src/test/java/com/ibm/sdwan/velocloud/service/impl/KafkaInternalMessagingServiceImplTest.java
> + 		kafkaInternalMessagingServiceImpl.sendEdgeStatusAsyncResponse(null);
Where is the exception you are expecting?

2022-09-14 10:01 UTC, lokanalla requested changes
Please comment on each comment I made and resolve them. Also still see some missing expectations and the Display content. Please work on them

2022-09-14 11:53 UTC, siddalasha commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +	@DisplayName("Testing positive scenario Execute URL for LIFECYCLE_OPERATION_DELETE_VCE_STATIC_IP")
it is  Exception  scenario. display name changed to  "Testing exception scenario to Execute URL for LIFECYCLE_OPERATION_DELETE_VCE_STATIC_IP"

2022-09-14 11:55 UTC, siddalasha commented on src/test/java/com/ibm/sdwan/velocloud/service/impl/KafkaInternalMessagingServiceImplTest.java
> + 		kafkaInternalMessagingServiceImpl.sendEdgeStatusAsyncResponse(null);
by giving Verify method , we can expect the exception

2022-09-14 12:08 UTC, siddalasha commented on src/test/java/com/ibm/sdwan/velocloud/driver/SDWanDriverTest.java
> +	@DisplayName("Testing positive scenario for ExecuteEdge - with exception")
yes positive scenario. display name changed to "Testing positive scenario for GET_EDGE"

2022-09-20 09:51 UTC, lokanalla commented on pom.xml
> +                        <exclude>com/ibm/sdwan/velocloud/utils/LogUtils.class</exclude>
Why have you excluded LogUtils class?

2022-09-21 11:51 UTC, lokanalla approved these changes

2022-09-21 11:52 UTC, merged